name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build
      run: |
        xcodebuild clean build -scheme SubtitlesMaster -destination 'platform=iOS Simulator,name=iPhone 14'

    - name: SwiftLint
      run: |
        if which swiftlint >/dev/null; then
          swiftlint
        else
          echo "warning: SwiftLint not installed"
        fi 